id: P29496699
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA21625
  instance_id: http://purl.bdrc.io/resource/IE21625
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - སྙན་རྩོམ་ལྷག་བསམ་དཀར་པོའི་རང་མདངས།
  alt_title:
    zh-hans:
    - 贡却桑 旦藏学诗歌选集
    en-x-mixed:
    - Mgo-log Dkon-mchog-bsam-gtan gyis sñan rtsom gces sgrig lhag bsam dkar poʼi
      raṅ mdaṅs źes bya ba bźugs so.
  author: http://purl.bdrc.io/resource/P7284
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    340fd49ec093461e904651b401c81c87:
      title: པོད ༡་སྙན་རྩོམ་ལྷག་བསམ་དཀར་པོའི་རང་མདངས།
      volume_number: 1
      base_file: UT21625_I1KG12356_0000.txt
      reference: http://purl.bdrc.io/resource/VL94C1AB348484BE1A
      image_group: I1KG12356
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW21625
  - http://purl.bdrc.io/resource/W21625
  ocr_software: Namsel
created_at: '2021-12-22T11:07:06.856767'
last_modified_at: '2021-12-22T11:07:06.856774'
